# Generated by Django 2.1.1 on 2019-03-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreceiptnotification',
            name='subscription_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='subscription.SubscriptionMember'),
        ),
    ]
