# Generated by Django 2.1.1 on 2019-03-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20190326_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailreceiptnotification',
            old_name='date_canceled',
            new_name='date_notified',
        ),
    ]
