# Generated by Django 2.1.1 on 2019-03-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20190326_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreceiptnotification',
            name='subscription_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='subscription.SubscriptionMember'),
        ),
        migrations.AlterField(
            model_name='emailreceiptnotification',
            name='trigger_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='djstripe.Event'),
        ),
    ]
