#Commented out frontend

version: '3'
services:

  backend:
    restart: 'no'
    build: backend/
    working_dir: /app/backend/
    command: bash -c "python check_db.py --service-name Postgres --ip database --port 5432 && 
        python manage.py runserver_plus 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
        - "DJANGO_SETTINGS_MODULE=backend.settings.development"
        - "FACEBOOK_CLIENT_ID=1974089579550206"
        - "FACEBOOK_CLIENT_SECRET=8117c08eed5c3ec4fe3142ee9d704dc1"
        - "SECRET_KEY=v(m)6f0+s3d$o4lk$lli&un$e1a@bu3oww^9=s=ms)+@df23*r"
        - "FIELD_ENCRYPTION_KEY=g2z7GI3SaOnTNDCEZhy_46NWSzyUatriWt_ecPTjHNo="
        - "STRIPE_ACCOUNT_SID=sk_test_9Xz79VxZxWJbanvxDAWLYmoN"
        - "STRIPE_SQUADUP_PRODUCT=prod_DwkQeS0ynwmGnR"
        - "DB_NAME=postgres"
        - "DB_USER=postgres"
        - "DB_HOST=database"
        - "DB_PORT=5432"

  database:
    restart: 'no'
    image: postgres
    ports:
      - "9432:5432"
