#Commented out frontend

version: '3'
services:

  backend:
    restart: always
    build: backend/
    working_dir: /app/backend/
    #dockerfile: Dockerfile-compose
    command: bash -c "python check_db.py --service-name Postgres --ip database --port 5432 && 
        python manage.py migrate && 
        python manage.py runserver_plus 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
        - DJANGO_SETTINGS_MODULE=backend.settings.development

  database:
    restart: always
    image: postgres
    ports:
      - "9432:5432"

  # frontend:
  #   build: frontend/
  #   volumes:
  #     - ./frontend/:/app/frontend
  #   working_dir: /app/frontend/
  #   command: sh ./expo.dev.sh
  #   ports:
  #     - "19002:19002"
  #   environment:
  #     - NODE_ENV=development
