#Commented out frontend

version: '3'
services:

  backend:
    restart: always
    build: backend/
    working_dir: /app/backend/
    command: bash -c "python check_db.py --service-name Postgres --ip database --port 5432 &&
                      python manage.py makemigrations core &&
                      python manage.py makemigrations verification_api &&
                      python manage.py makemigrations subscription_api &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    restart: always
    image: postgres
    ports:
      - "9432:5432"

  # nginx:
  #   restart: always
  #   image: nginx
  #   depends_on:
  #     - backend
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/config:/etc/nginx
