# Generated by Django 2.1.1 on 2019-03-05 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(editable=False, null=True)),
                ('date_for', models.DateTimeField(editable=False)),
                ('date_paid', models.DateTimeField(editable=False, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_payment_failed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Invoices',
                'ordering': ['date_for'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.IntegerField()),
                ('amount', models.FloatField()),
                ('is_voided', models.BooleanField(default=False)),
                ('is_free_trial', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.Invoice')),
                ('subscription_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='subscription.SubscriptionMember')),
            ],
            options={
                'db_table': 'Invoice_Items',
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'subscription_member')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('user', 'date_for')},
        ),
    ]
