# Generated by Django 2.1.1 on 2019-03-03 01:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 1, 19, 37, 480475, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 1, 19, 37, 480518, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 1, 19, 37, 481121, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 1, 19, 37, 481161, tzinfo=utc), editable=False),
        ),
    ]
