# Generated by Django 2.1.1 on 2019-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
