# Generated by Django 2.1.1 on 2019-03-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_invoice_stripe_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stripe_invoice',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
