# Generated by Django 2.1.1 on 2019-03-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20190302_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='date_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='date_modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
