# Generated by Django 2.1.1 on 2019-03-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20190318_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertax',
            old_name='state',
            new_name='state_tax',
        ),
    ]
