# Generated by Django 2.1.1 on 2019-03-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20190304_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='stripe_invoice_item',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stripe_invoice',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
    ]
