# Generated by Django 2.1.1 on 2019-03-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20190302_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_sent',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
