# Generated by Django 2.1.1 on 2019-03-03 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0004_auto_20190302_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountreceivable',
            name='user',
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_payment_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='account_receivable',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('user', 'date_for')},
        ),
        migrations.DeleteModel(
            name='AccountReceivable',
        ),
    ]
