# Generated by Django 2.1.1 on 2019-03-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20190304_2301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='subscription_member',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
