# Generated by Django 2.1.1 on 2019-03-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20190318_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
