# Generated by Django 2.1.1 on 2019-03-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20190305_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_fee_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stripe_invoice',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
