# Generated by Django 2.1.1 on 2019-03-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20190302_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_paid',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
