# Generated by Django 2.1.1 on 2019-03-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20190302_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
