# Generated by Django 2.1.1 on 2019-03-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20190305_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
