# Generated by Django 2.1.1 on 2019-03-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_invoice_stripe_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_finalized_at',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
