# Generated by Django 2.1.1 on 2019-03-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_invoiceitem_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='usage',
            field=models.IntegerField(),
        ),
    ]
