# Generated by Django 2.1.1 on 2019-03-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_auto_20190323_0615'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementrequest',
            name='subscription_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_requests', to='subscription.SubscriptionAccount'),
        ),
        migrations.AddField(
            model_name='managementrequest',
            name='subscription_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_requests', to='subscription.SubscriptionMember'),
        ),
    ]
