# Generated by Django 2.1.1 on 2019-03-27 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0002_auto_20190327_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementrequest',
            name='subscription_member',
        ),
        migrations.AddField(
            model_name='managementrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
