# Generated by Django 2.1.1 on 2019-03-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
