# Generated by Django 2.1.1 on 2019-03-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='billing_address',
            new_name='address_billing',
        ),
    ]
