# Generated by Django 2.1.1 on 2019-03-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190304_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
