# Generated by Django 2.1.1 on 2019-04-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190412_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.IntegerField(default=1555055494, null=True, verbose_name='date joined'),
        ),
    ]
