# Generated by Django 2.1.1 on 2019-03-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190228_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='address_billing',
            new_name='billing_address',
        ),
    ]
