# Generated by Django 2.1.1 on 2019-03-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190228_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='billing_address',
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='line_1',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='line_2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
