# Generated by Django 2.1.1 on 2019-03-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stripecustomer_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
