# Generated by Django 2.1.1 on 2019-03-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190228_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='country',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
