# Generated by Django 2.1.1 on 2019-03-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190228_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='last_four',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
