# Generated by Django 2.1.1 on 2019-04-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'ordering': ['-date_expires']},
        ),
        migrations.AddField(
            model_name='emailverification',
            name='date_created',
            field=models.IntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
