# Generated by Django 2.1.1 on 2019-04-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190416_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
