# Generated by Django 2.1.1 on 2018-10-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_user', to='authtoken.Token'),
        ),
    ]
