# Generated by Django 2.1.1 on 2018-10-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_verification_code',
        ),
    ]
