# Generated by Django 2.1.1 on 2018-11-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='owner',
            new_name='user',
        ),
    ]
