# Generated by Django 2.1.1 on 2018-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('validation_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
        ),
    ]
