# Generated by Django 2.1.1 on 2019-02-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementrequest',
            name='date_processed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
