# Generated by Django 2.1.1 on 2019-03-27 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='managementrequest',
            table='Management_Requests',
        ),
    ]
