# Generated by Django 2.1.1 on 2019-02-20 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20190219_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_requests_processed', to=settings.AUTH_USER_MODEL),
        ),
    ]
