# Generated by Django 2.1.1 on 2019-02-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20190219_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementrequest',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
