# Generated by Django 2.1.1 on 2019-03-31 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20190327_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
