# Generated by Django 2.1.1 on 2019-02-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_managementrequest_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementrequest',
            name='is_complete',
        ),
    ]
