# Generated by Django 2.1.1 on 2019-03-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stripecustomer_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='tax_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
