# Generated by Django 2.1.1 on 2018-10-16 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import subscription_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(max_length=64, null=True)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('date_subscription_start', models.DateTimeField(blank=True, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=32, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SquadDashboardElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_api.Squad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SquadMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(editable=False)),
                ('date_left', models.DateTimeField(blank=True, null=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_api.Squad')),
            ],
        ),
        migrations.CreateModel(
            name='StripePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_plan_id', models.CharField(blank=True, max_length=32, null=True)),
                ('billing_frequency', django_enumfield.db.fields.EnumField(default=3, enum=subscription_api.models.Frequency)),
                ('cost_price', models.FloatField(null=True)),
                ('cost_service_fee', models.FloatField(default=0)),
                ('tax_rate', models.FloatField(default=0)),
                ('cost_gross_total', models.FloatField(default=0)),
                ('cost_net_total', models.FloatField(default=0)),
                ('squad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_plan', to='subscription_api.Squad')),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=32, null=True)),
                ('stripe_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_api.StripePlan')),
            ],
        ),
        migrations.AddField(
            model_name='squadmember',
            name='stripe_subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_member', to='subscription_api.StripeSubscription'),
        ),
        migrations.AddField(
            model_name='squadmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
