# Generated by Django 2.1.1 on 2019-03-01 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import encrypted_model_fields.fields
import subscription.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('password', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('status_account', django_enumfield.db.fields.EnumField(default=2, enum=subscription.models.SubscriptionAccountStatus)),
                ('has_outstanding_balance', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('date_canceled', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'Subscription_Accounts',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_membership', django_enumfield.db.fields.EnumField(default=3, enum=subscription.models.MembershipStatus)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('date_canceled', models.DateTimeField(blank=True, editable=False, null=True)),
                ('subscription_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='subscription.SubscriptionAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPricingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('date_canceled', models.DateTimeField(blank=True, editable=False, null=True)),
                ('billing_frequency', django_enumfield.db.fields.EnumField(default=2, enum=subscription.models.PlanBillingFrequency)),
                ('maximum_size', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'Subscription_Pricing_Plans',
                'ordering': ['maximum_size'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', django_enumfield.db.fields.EnumField(default=0, enum=subscription.models.ServiceType)),
                ('free_trial_days', models.IntegerField(default=0)),
                ('url_home', models.CharField(max_length=128, null=True)),
                ('url_terms_of_service', models.CharField(max_length=128, null=True)),
                ('is_username_email', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Subscription_Services',
            },
        ),
        migrations.AddField(
            model_name='subscriptionpricingplan',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='subscription.SubscriptionService'),
        ),
        migrations.AddField(
            model_name='subscriptionaccount',
            name='price_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_accounts', to='subscription.SubscriptionPricingPlan'),
        ),
        migrations.AddField(
            model_name='subscriptionaccount',
            name='responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionaccount',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_accounts', to='subscription.SubscriptionService'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionpricingplan',
            unique_together={('service', 'amount', 'maximum_size')},
        ),
    ]
