# Generated by Django 2.1.1 on 2019-04-15 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=128)),
                ('date_created', models.IntegerField(editable=False)),
                ('date_modified', models.IntegerField(editable=False)),
                ('subscription_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='subscription.SubscriptionAccount')),
            ],
        ),
    ]
