# Generated by Django 2.1.1 on 2019-02-23 00:44

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPricingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('date_canceled', models.DateTimeField(blank=True, editable=False, null=True)),
                ('billing_frequency', django_enumfield.db.fields.EnumField(default=2, enum=subscription.models.PlanBillingFrequency)),
                ('maximum_size', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'Subscription_Pricing_Plans',
            },
        ),
        migrations.AddField(
            model_name='subscriptionservice',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionpricingplan',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='subscription.SubscriptionService'),
        ),
        migrations.AddField(
            model_name='subscriptionaccount',
            name='price_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_plan', to='subscription.SubscriptionPricingPlan'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionpricingplan',
            unique_together={('service', 'amount', 'maximum_size')},
        ),
    ]
