# Generated by Django 2.1.1 on 2019-04-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptioninvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvite',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
