# Generated by Django 2.1.1 on 2019-03-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionservice_stripe_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionservice',
            name='stripe_product',
            field=models.CharField(max_length=32),
        ),
    ]
