# Generated by Django 2.1.1 on 2019-04-15 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0003_subscriptioninvite_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptioninvite',
            old_name='user_email',
            new_name='recipient_email',
        ),
        migrations.AddField(
            model_name='subscriptioninvite',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptioninvite',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
