# Generated by Django 2.1.1 on 2019-04-17 04:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0004_auto_20190415_2319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionmember',
            unique_together={('user', 'subscription_account')},
        ),
    ]
