# Generated by Django 2.1.1 on 2019-04-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20190417_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionservice',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
