# Generated by Django 2.1.1 on 2019-04-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscriptionservice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionservice',
            name='url_signup',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
