# Generated by Django 2.1.1 on 2019-04-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_subscriptionservice_url_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
