# Generated by Django 2.1.1 on 2019-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_subscriptionservice_tag_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionaccount',
            name='live_mode',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='subscriptioninvite',
            name='live_mode',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='subscriptionmember',
            name='live_mode',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='date_created',
            field=models.IntegerField(default=1555697583, editable=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='date_modified',
            field=models.IntegerField(default=1555697583, editable=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='live_mode',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='subscriptionservice',
            name='date_created',
            field=models.IntegerField(default=1555697583, editable=False),
        ),
        migrations.AddField(
            model_name='subscriptionservice',
            name='date_modified',
            field=models.IntegerField(default=1555697583, editable=False),
        ),
        migrations.AddField(
            model_name='subscriptionservice',
            name='live_mode',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionaccount',
            name='date_created',
            field=models.IntegerField(default=1555697583, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionaccount',
            name='date_modified',
            field=models.IntegerField(default=1555697583, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptioninvite',
            name='date_created',
            field=models.IntegerField(default=1555697583, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptioninvite',
            name='date_modified',
            field=models.IntegerField(default=1555697583, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionmember',
            name='date_created',
            field=models.IntegerField(default=1555697583, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionmember',
            name='date_modified',
            field=models.IntegerField(default=1555697583, editable=False),
        ),
    ]
