# Generated by Django 2.1.1 on 2019-04-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_auto_20190419_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionaccount',
            name='date_created',
            field=models.IntegerField(default=1555697767, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionaccount',
            name='date_modified',
            field=models.IntegerField(default=1555697767, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptioninvite',
            name='date_created',
            field=models.IntegerField(default=1555697767, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptioninvite',
            name='date_modified',
            field=models.IntegerField(default=1555697767, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionmember',
            name='date_created',
            field=models.IntegerField(default=1555697767, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionmember',
            name='date_modified',
            field=models.IntegerField(default=1555697767, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='date_created',
            field=models.IntegerField(default=1555697767, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='date_modified',
            field=models.IntegerField(default=1555697767, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionservice',
            name='date_created',
            field=models.IntegerField(default=1555697767, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionservice',
            name='date_modified',
            field=models.IntegerField(default=1555697767, editable=False),
        ),
    ]
