# Generated by Django 2.1.1 on 2018-10-17 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification_api', '0004_phoneverificationcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverificationcode',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
