# Generated by Django 2.1.1 on 2018-11-24 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import encrypted_model_fields.fields
import subscription_api.models


class Migration(migrations.Migration):

    initial = True

    depends_on = (
        (settings.AUTH_USER_MODEL, '0001_initial'),
    )

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128, null=True)),
                ('secret', encrypted_model_fields.fields.EncryptedCharField(null=True)),
                ('service', models.CharField(max_length=16, null=True)),
                ('cost_price', models.IntegerField()),
                ('maximum_size', models.IntegerField(default=10)),
                ('current_size', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SquadMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enumfield.db.fields.EnumField(default=4, enum=subscription_api.models.SquadMemberStatus)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=32, null=True)),
                ('date_joined', models.DateTimeField(editable=False)),
                ('date_left', models.DateTimeField(blank=True, null=True)),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='subscription_api.Squad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_plan_id', models.CharField(blank=True, max_length=32, null=True)),
                ('billing_frequency', django_enumfield.db.fields.EnumField(default=2, enum=subscription_api.models.Frequency)),
                ('cost_cc_percent_fee', models.FloatField(default=0.03)),
                ('cost_cc_constant_fee', models.FloatField(default=0.5)),
                ('tax_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='squad',
            name='stripe_plan',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='subscription_api.StripePlan'),
        ),
    ]
