# Generated by Django 2.1.1 on 2018-12-12 00:48

from django.db import migrations
import django_enumfield.db.fields
import encrypted_model_fields.fields
import subscription_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0002_auto_20181124_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='service_type',
            field=django_enumfield.db.fields.EnumField(default=0, enum=subscription_api.models.SquadServiceType),
        ),
        migrations.AlterField(
            model_name='squad',
            name='secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
