# Generated by Django 2.1.1 on 2018-12-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0003_auto_20181211_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='maximum_size',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
