# Generated by Django 2.1.1 on 2018-12-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0006_auto_20181211_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='maximum_size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
