# Generated by Django 2.1.1 on 2019-01-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0010_squadmember_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
