# Generated by Django 2.1.1 on 2019-03-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailreceiptnotification',
            unique_together=set(),
        ),
    ]
