# Generated by Django 2.1.1 on 2019-03-21 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionservice_djstripe_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionservice',
            name='djstripe_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.Product'),
        ),
    ]
