# Generated by Django 2.1.1 on 2019-03-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20190321_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionservice',
            name='djstripe_product',
        ),
        migrations.AddField(
            model_name='subscriptionservice',
            name='stripe_product_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
