# Generated by Django 2.1.1 on 2019-03-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20190322_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionservice',
            name='stripe_product_id',
            field=models.CharField(max_length=32),
        ),
    ]
