# Generated by Django 2.1.1 on 2019-03-22 00:52

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20190322_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('date_canceled', models.DateTimeField(blank=True, editable=False, null=True)),
                ('billing_frequency', django_enumfield.db.fields.EnumField(default=2, enum=subscription.models.PlanBillingFrequency)),
                ('maximum_size', models.IntegerField(blank=True, default=None, null=True)),
                ('stripe_plan_id', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Subscription_Pricing_Plans',
                'ordering': ['maximum_size'],
            },
        ),
        migrations.RemoveField(
            model_name='subscriptionservice',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='subscriptionservice',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='subscriptionservice',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='subscription.SubscriptionService'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('service', 'amount', 'maximum_size')},
        ),
    ]
