# Generated by Django 2.1.1 on 2019-03-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20190322_0052'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='Subscription_Plans',
        ),
    ]
