# Generated by Django 2.1.1 on 2019-03-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_auto_20190322_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionaccount',
            name='is_connected_account',
        ),
    ]
