# Generated by Django 2.1.1 on 2019-03-22 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import subscription.enum


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0009_remove_subscriptionaccount_is_connected_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_membership', django_enumfield.db.fields.EnumField(default=30, enum=subscription.enum.MembershipStatus)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('date_canceled', models.DateTimeField(blank=True, editable=False, null=True)),
                ('stripe_subscription_item_id', models.CharField(blank=True, max_length=32, null=True)),
                ('subscription_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='subscription.SubscriptionAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Subscriptions',
            },
        ),
    ]
