# Generated by Django 2.1.1 on 2019-03-23 06:15

from django.db import migrations
import django_enumfield.db.fields
import subscription.enum


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_subscriptionmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmember',
            name='status_membership',
            field=django_enumfield.db.fields.EnumField(default=40, enum=subscription.enum.MembershipStatus),
        ),
    ]
