# Generated by Django 2.1.1 on 2019-03-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_auto_20190323_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmember',
            name='stripe_subscription_item_id',
            field=models.CharField(max_length=32),
        ),
    ]
