# Generated by Django 2.1.1 on 2019-03-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20190326_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmember',
            name='stripe_subscription_item_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
