# Generated by Django 2.1.1 on 2018-10-20 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import subscription_api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('squad_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64, null=True)),
                ('maximum_size', models.IntegerField(default=10)),
                ('current_size', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('date_subscription_start', models.DateTimeField(blank=True, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=32, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SquadMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=32, null=True)),
                ('date_joined', models.DateTimeField(editable=False)),
                ('date_left', models.DateTimeField(blank=True, null=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_api.Squad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_plan_id', models.CharField(blank=True, max_length=32, null=True)),
                ('billing_frequency', django_enumfield.db.fields.EnumField(default=2, enum=subscription_api.models.Frequency)),
                ('cost_price', models.FloatField(null=True)),
                ('cost_service_fee', models.FloatField(default=0)),
                ('tax_rate', models.FloatField(default=0)),
                ('cost_gross_total', models.FloatField(default=0)),
                ('cost_net_total', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='squad',
            name='stripe_plan',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='subscription_api.StripePlan'),
        ),
    ]
