# Generated by Django 2.1.1 on 2018-10-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='description',
        ),
        migrations.AddField(
            model_name='squad',
            name='service',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
