# Generated by Django 2.1.1 on 2018-10-23 00:28

from django.db import migrations
import django_enumfield.db.fields
import subscription_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0002_auto_20181022_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadmember',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=subscription_api.models.SquadMemberStatus),
        ),
    ]
