# Generated by Django 2.1.1 on 2018-10-23 00:35

from django.db import migrations
import django_enumfield.db.fields
import subscription_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0003_squadmember_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadmember',
            name='status',
        ),
        migrations.AddField(
            model_name='squadmember',
            name='membership_status',
            field=django_enumfield.db.fields.EnumField(default=1, enum=subscription_api.models.SquadMemberStatus),
        ),
    ]
