# Generated by Django 2.1.1 on 2018-10-23 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0004_auto_20181022_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='squad',
            name='subscription_login',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='subscription_api.SubscriptionLogin'),
            preserve_default=False,
        ),
    ]
