# Generated by Django 2.1.1 on 2018-10-23 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0005_auto_20181022_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='subscription_login',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='subscription_api.SubscriptionLogin'),
        ),
    ]
