# Generated by Django 2.1.1 on 2018-10-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0006_auto_20181022_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='subscription_login',
        ),
        migrations.AddField(
            model_name='squad',
            name='password',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squad',
            name='username',
            field=models.CharField(default='empty', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubscriptionLogin',
        ),
    ]
