# Generated by Django 2.1.1 on 2018-10-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0007_auto_20181022_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squadmember',
            old_name='membership_status',
            new_name='status',
        ),
    ]
