# Generated by Django 2.1.1 on 2018-10-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0008_auto_20181022_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='squad',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
