# Generated by Django 2.1.1 on 2018-12-15 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0008_squad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_squads', to=settings.AUTH_USER_MODEL),
        ),
    ]
