# Generated by Django 2.1.1 on 2018-10-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0009_auto_20181027_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='payment_method',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
