# Generated by Django 2.1.1 on 2018-11-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0010_squad_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
