# Generated by Django 2.1.1 on 2018-11-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0011_squad_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeplan',
            name='cost_gross_total',
        ),
        migrations.RemoveField(
            model_name='stripeplan',
            name='cost_net_total',
        ),
        migrations.RemoveField(
            model_name='stripeplan',
            name='cost_service_fee',
        ),
        migrations.AddField(
            model_name='stripeplan',
            name='cost_cc_processing_fee',
            field=models.FloatField(default=0.05),
        ),
    ]
