# Generated by Django 2.1.1 on 2019-01-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0011_squad_is_fake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='service',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
