# Generated by Django 2.1.1 on 2018-11-10 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0012_auto_20181108_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
