# Generated by Django 2.1.1 on 2018-11-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0015_squad_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeplan',
            name='cost_cc_processing_fee',
        ),
        migrations.AddField(
            model_name='stripeplan',
            name='cost_cc_constant_fee',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='stripeplan',
            name='cost_cc_percent_fee',
            field=models.FloatField(default=0.03),
        ),
    ]
