# Generated by Django 2.1.1 on 2018-11-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0016_auto_20181117_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
