# Generated by Django 2.1.1 on 2018-11-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0017_squad_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='payment_method',
        ),
    ]
