# Generated by Django 2.1.1 on 2018-11-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0018_remove_squad_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='service',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
