# Generated by Django 2.1.1 on 2018-11-24 01:19

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import subscription_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0019_auto_20181119_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadmember',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='subscription_api.Squad'),
        ),
        migrations.AlterField(
            model_name='squadmember',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=2, enum=subscription_api.models.SquadMemberStatus),
        ),
    ]
