# Generated by Django 2.1.1 on 2018-11-24 06:02

from django.db import migrations
import django_enumfield.db.fields
import subscription_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_api', '0021_auto_20181123_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadmember',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=4, enum=subscription_api.models.SquadMemberStatus),
        ),
    ]
