# Generated by Django 2.1.1 on 2019-03-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionservice',
            name='stripe_product',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
