# Generated by Django 2.1.1 on 2019-03-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20190305_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpricingplan',
            name='stripe_plan',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
