# Generated by Django 2.1.1 on 2019-03-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20190305_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmember',
            name='stripe_subscription_item_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
