# Generated by Django 2.1.1 on 2019-03-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscriptionmember_stripe_subscription_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionservice',
            name='stripe_product',
        ),
    ]
