# Generated by Django 2.1.1 on 2019-03-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_remove_subscriptionservice_stripe_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpricingplan',
            name='stripe_plan',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
