# Generated by Django 2.1.1 on 2019-03-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_auto_20190305_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionaccount',
            name='is_connected_account',
            field=models.BooleanField(default=False),
        ),
    ]
