# Generated by Django 2.1.1 on 2019-03-17 22:56

from django.db import migrations
import django_enumfield.db.fields
import subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_subscriptionaccount_is_connected_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionaccount',
            name='status_account',
            field=django_enumfield.db.fields.EnumField(default=20, enum=subscription.models.SubscriptionAccountStatus),
        ),
    ]
