# Generated by Django 2.1.1 on 2019-03-17 23:03

from django.db import migrations
import django_enumfield.db.fields
import subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_auto_20190317_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmember',
            name='status_membership',
            field=django_enumfield.db.fields.EnumField(default=30, enum=subscription.models.MembershipStatus),
        ),
    ]
