# Generated by Django 2.1.1 on 2019-03-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_auto_20190317_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionaccount',
            name='price_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_accounts', to='subscription.SubscriptionPricingPlan'),
        ),
    ]
