# Generated by Django 2.1.1 on 2019-03-20 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_auto_20190318_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionaccount',
            name='price_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_accounts', to='subscription.SubscriptionPricingPlan'),
        ),
        migrations.AlterField(
            model_name='subscriptionmember',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
