# Generated by Django 2.1.1 on 2019-03-18 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(editable=False, null=True)),
                ('date_for', models.DateTimeField(editable=False)),
                ('date_paid', models.DateTimeField(editable=False, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_payment_failed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('stripe_invoice', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('stripe_invoice_number', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('stripe_invoice_finalized_at', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('stripe_invoice_fee_id', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Invoices',
                'ordering': ['date_for'],
            },
        ),
        migrations.CreateModel(
            name='StateTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=512, unique=True)),
                ('sales_tax', models.FloatField()),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'StateTaxes',
            },
        ),
        migrations.CreateModel(
            name='UserTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('state_sales_tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxable_users', to='accounting.StateTax')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserTaxes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('user', 'date_for')},
        ),
    ]
