# Generated by Django 2.1.1 on 2019-03-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20190318_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertax',
            name='state_tax',
        ),
        migrations.RemoveField(
            model_name='usertax',
            name='user',
        ),
        migrations.DeleteModel(
            name='StateTax',
        ),
        migrations.DeleteModel(
            name='UserTax',
        ),
    ]
