# Generated by Django 2.1.1 on 2018-12-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, verbose_name='facebook id'),
        ),
    ]
