# Generated by Django 2.1.1 on 2018-11-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181027_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='facebook id'),
        ),
    ]
