# Generated by Django 2.1.1 on 2018-11-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181106_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_mature_content',
            field=models.BooleanField(default=False),
        ),
    ]
