# Generated by Django 2.1.1 on 2018-11-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_can_view_mature_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_billing',
        ),
        migrations.DeleteModel(
            name='AddressBilling',
        ),
    ]
