# Generated by Django 2.1.1 on 2018-11-09 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181108_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.StripeCustomer'),
        ),
    ]
