# Generated by Django 2.1.1 on 2018-10-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_phone_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_code',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
