# Generated by Django 2.1.1 on 2018-11-13 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181112_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='billing_address',
        ),
        migrations.AddField(
            model_name='user',
            name='address_billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_user', to='core.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_user', to='core.Address'),
        ),
    ]
