# Generated by Django 2.1.1 on 2018-11-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181112_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'managed': True},
        ),
    ]
