# Generated by Django 2.1.1 on 2018-11-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181112_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_billing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core.BillingAddress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_shipping',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core.ShippingAddress'),
        ),
    ]
