# Generated by Django 2.1.1 on 2018-11-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181112_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_view_mature_content',
        ),
    ]
