# Generated by Django 2.1.1 on 2018-11-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, editable=False, max_length=30, verbose_name='facebook id'),
        ),
    ]
