# Generated by Django 2.1.1 on 2018-11-24 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181118_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_billing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core.BillingAddress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_shipping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core.ShippingAddress'),
        ),
    ]
